# Generated by Django 4.0.3 on 2022-06-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature_discount'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='clients', through='authentication.ClientQrCodeCount', to='core.feature'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.tarif'),
        ),
    ]
