# Generated by Django 4.0.3 on 2022-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_companyprofile_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='tarif_expiring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='tarif_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
