# Generated by Django 4.0.3 on 2022-06-06 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='day_count',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default='Desc'),
            preserve_default=False,
        ),
    ]
