# Generated by Django 4.0.3 on 2022-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature_day_count_feature_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
