# Generated by Django 4.0.3 on 2022-06-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tarif_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='day_count',
        ),
    ]
